import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "React App", //*Titulo de la app
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen w-full flex items-center justify-center flex-wrap">
      <body className='h-auto  w-screen flex items-center content-center justify-center flex-wrap overflow-hidden'>{children}</body>
    </html>
  );
}
